### ISSUE TITLE
Gestion des utilisateurs [GU.1]

### ISSUE THREAD

**Issue by CyrilDegout** [jpdurot/keyboard-sampler#6]
[GU.1] Pouvoir se logguer sur l'application avec un compte personnel
- Avoir une page de login
- Une base de login valides (ça peut être géré en dur dans un premier temps)

**Comment by jpdurot** [comment]
Bon, on peut pas assigner 2 personnes, mais y'a Nico et Ludo :)

**Comment by CyrilDegout** [comment]
ça a l'air d'être bien avancé, ça marche maintenant alors ?

**Comment by ludovicderochethales** [comment]
Il reste la gestion du mot de passe et un bouton logout à mettre. Sinon
c'est fonctionnel oui

**Comment by NicolasBeaudrot** [comment]
Déconnexion et Modifier mot de passe ont été implémenté
